#!/usr/bin/env bash
# this  script overrides the default nginx welcome html page
sudo apt-get update
sudo apt-get install nginx
sudo apt-get install curl
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
