#!/usr/bin/env bash
# this  script overrides the default nginx welcome html page
sudo apt-get update -y
sudo apt-get install nginx -y
sudo apt-get install upgrade -y
sudo service nginx start
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
