#!/bin/bash

# Update the system packages
sudo apt update

# Install NGINX web server
sudo apt install nginx -y

# Create a custom 404 page
sudo tee /var/www/html/404.html > /dev/null <<EOT
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page.</p>
</body>
</html>
EOT

# Update NGINX default configuration to include the custom 404 page
sudo sed -i 's|#error_page 404 /404.html;|error_page 404 /404.html;|' /etc/nginx/sites-available/default

# Test the NGINX configuration
sudo nginx -t

# Restart NGINX to apply the configuration changes
sudo systemctl restart nginx.service

