#!/usr/bin/env bash
# this  script overrides the default nginx welcome html page
#ssh ubuntu@54.175.17.40
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo service nginx start
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '16i \\tadd_header X-Served-By $hostname' /etc/nginx/nginx.conf

