#!/usr/bin/env bash
# this  script creates a header in nginx config file
#ssh ubuntu@54.175.17.40
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i '16i \\\tadd_header X-Served-By $hostname' /etc/nginx/nginx.conf
sudo service nginx restart
