#!/usr/bin/env bash
#Configure HAProxy load balancer server using script
apt-get install -y software-properties-common
add-apt-repository  -y ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get -y install haproxy=2.8.\*
echo "frontend spaced
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 180489-web-01 54.152.132.85:80 check
        server 180489-web-02 54.144.86.206:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
