#!/usr/bin/env bash
#Configure HAProxy load balancer server using script
sudo apt-get -y update
sudo apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get install haproxy=2.8.\*
sudo apt-get -y install haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "  listen loadbalancer
        bind *:80
        mode http
        balance roundrobin
        server 180489-web-01 54.152.132.85:80 check
        server 180489-web-02 54.144.86.206:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
