#!/usr/bin/env bash
# A script that creates a backup of all databases
mysqldump -u root -p "$1" --all-databases > backup.sql
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql_root_password>"
    exit 1
fi
current_date=$(date +'%d-%m-%Y')
tar -czf "$current_date.tar.gz" backup.sql
