#!/usr/bin/env bash
# Configure container to listen at 80 for all ipv4 requests in 5 lines
ln -f /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx reload
service nginx stop
