#!/usr/bin/env bash
# This script loops 10 times displaying bad luck, good luck and Best School
i=11
while((i>1))
	do
		if [[ $i == 4 ]]
		then
			echo "bad luck"
		elif [[ $i == 8 ]]
		then
			echo "good luck"
		else
			echo "Best School"
		fi
		((i--))
done
