#!/usr/bin/env bash
# This script loops 10 times displaying bad luck, good luck and Best School
for ((i=1; i<11; i++))
	do
		if [[ $i == 4 ]]
		then
			echo "bad luck"
		elif [[ $i == 8 ]]
		then
			echo "good luck"
		else
			echo "Best School"
		fi
done
