#!/usr/bin/env bash
# This script loops 10 times displaying bad luck, good luck and Best School
t=0

while ((t < 13))
	do
		s=0
		while ((s<60))
			do
				if [[ $s == 0 ]]
				then
					echo "Hour: $t"
				else
					echo $s
				fi
				((s++))
			done
	((t++))
	done
