#!/usr/bin/env bash
# Fix a broken nginx container to listen for all ports at 8080
sudo kill $(sudo lsof -t -i :80)
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
