#!/usr/bin/env bash
# Fix a broken nginx container to listen for all ports at 8080
sudo useradd nginx >/dev/null 2>&1
sudo chown nginx /etc/nginx/nginx.conf
sudo chmod u+r /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
