#!/usr/bin/env bash
# This file serves from /airbnb-onepage/ route for our flask application
server {
	listen 80;
	server_name 127.0.0.1 54.175.146.194;

	location /airbnb-onepage/{
		 proxy_pass http://127.0.0.1:5000;
#	        proxy_set_header Host $host;
#        	proxy_set_header X-Real-IP $remote_addr;
#	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#	        proxy_set_header X-Forwarded-Proto $scheme;	
	}
	location /airbnb-dynamic/number_odd_or_even/ {
		proxy_pass http://127.0.0.1:5001;
	}
}

